services:
  yolo-gateway-1:
    image: yolo/yolo-gateway
    container_name: yolo-gateway-1
    hostname: yolo-gateway-1
    environment:
      - GATEWAY_HOSTNAME=yolo-gateway-1
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://yolo-registry-1:8761/eureka/,http://yolo-registry-2:8761/eureka/,http://yolo-registry-3:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - yolo-net


  yolo-gateway-2:
    image: yolo/yolo-gateway
    container_name: yolo-gateway-2
    hostname: yolo-gateway-2
    environment:
      - GATEWAY_HOSTNAME=yolo-gateway-2
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://yolo-registry-1:8761/eureka/,http://yolo-registry-2:8761/eureka/,http://yolo-registry-3:8761/eureka/
    ports:
      - "8081:8080"
    networks:
      - yolo-net

  yolo-gateway-3:
    image: yolo/yolo-gateway
    container_name: yolo-gateway-3
    hostname: yolo-gateway-3
    environment:
      - GATEWAY_HOSTNAME=yolo-gateway-3
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://yolo-registry-1:8761/eureka/,http://yolo-registry-2:8761/eureka/,http://yolo-registry-3:8761/eureka/
    ports:
      - "8082:8080"
    networks:
      - yolo-net

networks:
  yolo-net:
    external: true

