services:
  yolo-nginx-1:
    image: yolo/yolo-nginx
    container_name: yolo-nginx-1
    hostname: yolo-nginx-1
    ports:
      - "8888:80"
    networks:
      - yolo-net

networks:
  yolo-net:
    external: true
