management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      enabled: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka-server-port}/eureka/
    eureka-server-port: 8081
  instance:
    hostname: localhost
    appname: yolo-gateway
    prefer-ip-address: true

