eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka/,${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    app-name: yolo-registry

server:
  port: ${EUREKA_SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always


spring:
  application:
    name: yolo-registry